"use client";
import {useEffect,useState} from "react";
const today=()=>new Date().toISOString().slice(0,10);
export default function BookingClient(){
 const [date,setDate]=useState(today()); const [slots,setSlots]=useState<any[]>([]); const [time,setTime]=useState(""); const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [msg,setMsg]=useState<any>(null); const [loading,setLoading]=useState(false);
 async function load(){const r=await fetch(`/api/slots?date=${date}`,{cache:"no-store"}); setSlots(await r.json()); setTime("");}
 useEffect(()=>{load()},[date]);
 async function book(e:React.FormEvent){e.preventDefault(); setLoading(true); setMsg(null); const r=await fetch("/api/appointments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({patientName:name,patientPhone:phone,date,time})}); const j=await r.json(); setLoading(false); if(!r.ok){setMsg({error:j.error}); await load(); return;} setMsg({ok:`Booked successfully. Your token is ${j.tokenNumber}.`}); setName("");setPhone("");setTime("");await load();}
 return <div className="grid"><section className="card"><p className="muted">General Physician</p><h1 style={{marginTop:0}}>Dr. Ravi Kumar</h1><div className="field"><label>Choose date</label><input type="date" min={today()} value={date} onChange={e=>setDate(e.target.value)}/></div><h3>Available slots</h3><div className="slots">{slots.map(s=><button key={s.time} disabled={!s.available} className={`slot ${time===s.time?"selected":""}`} onClick={()=>setTime(s.time)}>{s.time}</button>)}</div></section><section className="card"><h2>Book appointment</h2><p className="muted">Selected: {date} {time||"— choose a time"}</p><form onSubmit={book}><div className="field"><label>Patient name</label><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></div><div className="field"><label>Phone number</label><input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="9876543210"/></div><button className="btn" disabled={!time||loading}>{loading?"Booking...":"Book appointment"}</button></form>{msg?.ok&&<div className="success">{msg.ok}</div>}{msg?.error&&<div className="error">{msg.error}</div>}</section></div>
}
